// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaranzaSoul;

namespace TaranzaSoul.Migrations
{
    [DbContext(typeof(UserLogContext))]
    partial class UserLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("TaranzaSoul.Users", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ApprovalModId");

                    b.Property<string>("ApprovalReason");

                    b.Property<bool>("ApprovedAccess");

                    b.Property<bool>("NewAccount");

                    b.HasKey("UserId");

                    b.ToTable("UserList");
                });

            modelBuilder.Entity("TaranzaSoul.WatchedUsers", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Reason");

                    b.HasKey("UserId");

                    b.ToTable("WatchedUserList");
                });
#pragma warning restore 612, 618
        }
    }
}
